name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Hier den Namen Ihrer Haupt-Branch angeben

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Hier den Befehl zum Erstellen Ihres Projekts angeben

      - name: Deploy
        run: |
          mkdir -p deploy  # Erstellen Sie das Verzeichnis, in das Sie den Build verschieben möchten
          mv path/to/build/directory/* deploy/  # Verschieben Sie den Build in das deploy-Verzeichnis

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy  # Geben Sie hier den Pfad zum Build-Verzeichnis an
